#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'ant'
cookbook 'apache2'
cookbook 'apt'
cookbook 'coldfire-dev', :git => 'https://github.com/nmische/chef-coldfire-dev.git'
cookbook 'coldfusion10', :git => 'https://github.com/wharton/chef-coldfusion10.git'
cookbook 'git'
cookbook 'java'
cookbook 'mxunit', :git => 'https://github.com/wharton/chef-mxunit.git'
cookbook 'openssl'
cookbook 'railo334', :git => 'https://github.com/nmische/chef-railo334.git'
cookbook 'rng-tools'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
